# Numpy tutorial 

* first of all import the numpy liberary

In [2]:
import numpy as np

##### Arange make an arry of number in arithmetic progression

In [3]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

##### Linespace return an arrey spaced equally

In [4]:
arr2 = np.linspace(2, 12 , 4)
arr2

array([ 2.        ,  5.33333333,  8.66666667, 12.        ])

Return the matrix of zeros for specified size

In [5]:
matrix = np.zeros((3, 4))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
matrix2 = np.ones((4, 5))
print(matrix2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
m2 = np.reshape(matrix, (2, 6))
m2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
np.sum(matrix2)

20.0

Return the average of all the elements of array

In [9]:
np.mean(matrix2)

1.0

In [10]:
matrix[0, :] = [1, 4 , 1, 5]
matrix[1, :] = [3, 2, 1 ,2]
matrix[2, :] = [2, 4, 2, 5]
matrix[1, 2] = 3
print(matrix)

[[1. 4. 1. 5.]
 [3. 2. 3. 2.]
 [2. 4. 2. 5.]]


Transpose of the matrix

In [11]:
mat = matrix.T
mat

array([[1., 3., 2.],
       [4., 2., 4.],
       [1., 3., 2.],
       [5., 2., 5.]])

In [12]:
mat.reshape(3, 4)

array([[1., 3., 2., 4.],
       [2., 4., 1., 3.],
       [2., 5., 2., 5.]])

In [32]:
mat.shape

(4, 3)

In [13]:
row = np.array([5, 2, 3, 4])
column = np.array([[5], [2], [3], [4]])
print(f"m1 {matrix}")
print(f"m2 {mat}")
m1 = np.vstack((matrix, row))
m2 = np.hstack((mat, column))
print(m1)
m2

m1 [[1. 4. 1. 5.]
 [3. 2. 3. 2.]
 [2. 4. 2. 5.]]
m2 [[1. 3. 2.]
 [4. 2. 4.]
 [1. 3. 2.]
 [5. 2. 5.]]
[[1. 4. 1. 5.]
 [3. 2. 3. 2.]
 [2. 4. 2. 5.]
 [5. 2. 3. 4.]]


array([[1., 3., 2., 5.],
       [4., 2., 4., 2.],
       [1., 3., 2., 3.],
       [5., 2., 5., 4.]])

## Implimenting liner algebra 

return determinant 

In [14]:
np.linalg.det(m1)

-3.9999999999999902

In [15]:
np.linalg.det(m2)

-4.000000000000004

In [16]:
me=np.array([[1, 3],[2, 5]])
print(me)
np.linalg.eig(me)

[[1 3]
 [2 5]]


EigResult(eigenvalues=array([-0.16227766,  6.16227766]), eigenvectors=array([[-0.93246475, -0.50245469],
       [ 0.36126098, -0.86460354]]))

In [17]:
np.linalg.inv(m2)

array([[ 4. ,  5.5, -5. , -4. ],
       [ 1.5,  2.5, -1.5, -2. ],
       [-5. , -6.5,  6. ,  5. ],
       [ 0.5,  0. , -0.5,  0. ]])

In [18]:
m1.dtype

dtype('float64')

In [19]:
m1.size

16

In [20]:
m1.shape

(4, 4)

In [21]:
m2.shape

(4, 4)

It returen the dimention of the array


In [22]:
m1.ndim

2

In [23]:
print(m1)
m2

[[1. 4. 1. 5.]
 [3. 2. 3. 2.]
 [2. 4. 2. 5.]
 [5. 2. 3. 4.]]


array([[1., 3., 2., 5.],
       [4., 2., 4., 2.],
       [1., 3., 2., 3.],
       [5., 2., 5., 4.]])

In [24]:
print(np.add(m1, m2))
print(np.subtract(m1, m2))
print(np.multiply(m1, m2))
print(np.divide(m1, m2))

[[ 2.  7.  3. 10.]
 [ 7.  4.  7.  4.]
 [ 3.  7.  4.  8.]
 [10.  4.  8.  8.]]
[[ 0.  1. -1.  0.]
 [-1.  0. -1.  0.]
 [ 1.  1.  0.  2.]
 [ 0.  0. -2.  0.]]
[[ 1. 12.  2. 25.]
 [12.  4. 12.  4.]
 [ 2. 12.  4. 15.]
 [25.  4. 15. 16.]]
[[1.         1.33333333 0.5        1.        ]
 [0.75       1.         0.75       1.        ]
 [2.         1.33333333 1.         1.66666667]
 [1.         1.         0.6        1.        ]]


In [25]:
print(m1+m2)

[[ 2.  7.  3. 10.]
 [ 7.  4.  7.  4.]
 [ 3.  7.  4.  8.]
 [10.  4.  8.  8.]]


In [26]:
m1-m2

array([[ 0.,  1., -1.,  0.],
       [-1.,  0., -1.,  0.],
       [ 1.,  1.,  0.,  2.],
       [ 0.,  0., -2.,  0.]])

*Eliment wise multiplication

In [27]:
m1*m2

array([[ 1., 12.,  2., 25.],
       [12.,  4., 12.,  4.],
       [ 2., 12.,  4., 15.],
       [25.,  4., 15., 16.]])

@Matirx multiplication

In [28]:
m1@m2

array([[43., 24., 45., 36.],
       [24., 26., 30., 36.],
       [45., 30., 49., 44.],
       [36., 36., 44., 54.]])

In [29]:
m3 = np.random.rand(3, 4)
m3

array([[0.52676412, 0.30991572, 0.39572922, 0.44616076],
       [0.36781385, 0.03133743, 0.97152651, 0.14125715],
       [0.17794346, 0.53259899, 0.19939221, 0.81986775]])

In [30]:
np.random.shuffle(m3)
m3

array([[0.17794346, 0.53259899, 0.19939221, 0.81986775],
       [0.52676412, 0.30991572, 0.39572922, 0.44616076],
       [0.36781385, 0.03133743, 0.97152651, 0.14125715]])

In [31]:
np.median(m3)

0.38177153527942753